### ISSUE TITLE
Request for Unified Login Clone

### ISSUE THREAD

**Issue by Ajayveer9911github** [codewithweeb/WeebZone#1]
Sir, 

- [ ] Add **Unified Login Clone** feature for

> AppDrive/DriveApp/GDFlix/DriveAce/DriveLinks/DriveBit/DriveSharer/Anidrive/Driveroot/Driveflix/Indidrive/drivehub(in)/HubDrive/DriveHub(ws)/KatDrive/Kolop/DriveFire/DriveBuzz/SharerPw

And try to 
- [ ] Add **unzip/zip support** for above **links** like _GDtot_.

**Comment by codewithweeb** [comment]
these feature are buggy 
earlier it was present in my repo but i remove it bcz many times it unable to clone the files 
i can try another method to implement this later on
if any one is interested to contribute in repo just make Pull request i will merge it

**Comment by Ajayveer9911github** [comment]
Okay. Can you at least add [indidrive.in](https://indidrive.in/) support?

**Comment by codewithweeb** [comment]
i will try 👍

**Comment by codewithweeb** [comment]
send any indidrive file link for testing

**Comment by Ajayveer9911github** [comment]
https://indidrive.in/file/4Etdo8SjLryRT29bTHhp

**Comment by Ajayveer9911github** [comment]
> send any indidrive file link for testing

https://indidrive.in/file/4Etdo8SjLryRT29bTHhp

**Comment by Ajayveer9911github** [comment]
> send any indidrive file link for testing

https://indidrive.in/dfile/aDSHalLPB2HNbSxcVEGHKmjOtmIWpfiRxenzoq3V

**Comment by Ajayveer9911github** [comment]
Unified still not working. Sent one indidrive link
![unified issue](https://user-images.githubusercontent.com/96938395/184954208-1ec1f6d1-43b0-4b23-aa9f-2848d480f62a.PNG)
