### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by BangKuntet** [codewithweeb/WeebZone#13]
# HUBDRIVE COOKIES
HUBDRIVE_CRYPT = ""

# (KATDRIVE + KOLOP + DRIVEHUB) COOKIES
KATDRIVE_CRYPT = ""

# (DRIVEFIRE + DRIVEBUZZ) COOKIES
DRIVEFIRE_CRYPT = ""

And Shortener

how to fill this config and where the link for drive ???
maybe can you make tutorial video to get this

sorry i am newbie

**Comment by codewithweeb** [comment]
don't open ask issue 
for help join our group https://t.me/weebzonemir

for these value check in readme 
https://github.com/codewithweeb/WeebZone/wiki/Setting-up-the-config.env-file#unified-login-appdrive-driveapp-gdflix-drivebit-drivelinks-drivesharer-driveace-drivepro-sharer
