### ISSUE TITLE
heroku usage command issue ?

### ISSUE THREAD

**Issue by MonarchCloudx** [codewithweeb/WeebZone#18]
getting this from usage command
Please insert your HEROKU_APP_NAME and HEROKU_API_KEY in Vars

should i add this by myself  in config  ??

**Comment by codewithweeb** [comment]
use my repo heroku branch to deploy the bot bcz it automatically it in config no need to add in config

**Comment by MonarchCloudx** [comment]
using heroku branch

**Comment by codewithweeb** [comment]
so add it manually in config 
HEROKU_APP_NAME = ""
HEROKU_API_KEY = ""

**Comment by MonarchCloudx** [comment]
ok
