### ISSUE TITLE
Buggggggg

### ISSUE THREAD

**Issue by BangKuntet** [codewithweeb/WeebZone#23]
Plz Answer How To fill this and give the link shit

# HUBDRIVE COOKIES
HUBDRIVE_CRYPT = ""

# (KATDRIVE + KOLOP + DRIVEHUB) COOKIES
KATDRIVE_CRYPT = ""

# (DRIVEFIRE + DRIVEBUZZ) COOKIES
DRIVEFIRE_CRYPT = ""

# Force Sub Channel
FSUB = ""
CHANNEL_USERNAME = ""
FSUB_CHANNEL_ID =

#BRANDING
CREDIT_NAME = "" 

#DYNAMIC IMAGES
PICS = ""               #Add multiple telgraph image links that are seperated by spaces

**Comment by codewithweeb** [comment]
read the readme bro
