### ISSUE TITLE
[Improvement] Is it possible to add file size limit in leech ?

### ISSUE THREAD

**Issue by RealNoobieDrive** [codewithweeb/WeebZone#35]
Suppose I am Leeching a folder of 50 gb of 10 files in it, if i have set leech file limit to 4gb ,,so only file which is less than 4gb will be leeched rest will not.

It will be very helpful as splitting again causing ban in leech.

**Comment by codewithweeb** [comment]
don't worry no more splitting cause because soon heroku free dyno over then u have to shift to vps
till now enjoy the same repo as it
