### ISSUE TITLE
deploy by Github WorkFlow

### ISSUE THREAD

**Issue by TTDIDTG** [codewithweeb/WeebZone#36]
![‏‏צילום מסך (105)](https://user-images.githubusercontent.com/98256431/188396859-611741b6-5bd1-404b-888a-99e08f464eee.png)
those erorros
Error: Process completed with exit code 128
Error: Process completed with exit code 1.

**Comment by codewithweeb** [comment]
BOT_REPO is not correct
read the readme section for correct way of filling

**Comment by TTDIDTG** [comment]
Do it to my private repo?
Or main public repo?
Thank!

**Comment by codewithweeb** [comment]
public fork repo
